export const iconType = {
  bug: "🐛",
  dark: "🌑",
  dragon: "🐉",
  electric: "⚡",
  fairy: "🧚",
  fighting: "👊",
  fire: "🔥",
  flying: "🦅",
  ghost: "👻",
  grass: "🌿",
  ground: "🌍",
  ice: "❄️",
  normal: "🧑",
  poison: "☠️",
  psychic: "🧠",
  rock: "🪨",
  steel: "🛡️",
  water: "💧",
  stellar: "🌟",
  unknown: "❓",
}